--- !<MUTATOR>
contentType: "MUTATOR"
firstIndex: "2019-02-19 19:31"
variationOf: null
game: "Unreal Tournament 2004"
name: "Custom Config - change settings for in-game play."
author: "Unknown"
description: ""
releaseDate: "2003-07"
attachments: []
originalFilename: "customconfig_v11.zip"
hash: "d981c36283fdac62309bcb358109b1e19765947c"
fileSize: 8190
files:
- name: "CustomConfig.u"
  fileSize: 16677
  hash: "8718eb0786c886d1ee88660e2558d3e40bd4db3d"
otherFiles: 4
downloads:
- url: "https://f002.backblazeb2.com/file/unreal-archive-files/Unreal%20Tournament%202004/Mutators/C/customconfig_v11.zip"
  main: true
  repack: false
  state: "OK"
deleted: false
mutators:
- name: "Custom Config - change settings for in-game play."
  description: ""
weapons: []
vehicles: []
hasConfigMenu: false
hasKeybinds: false
